Stripe endpoint
IntersysConsulting/ingangsters-api pull request #79
Opened 2019-10-22 14:18 UTC by sofia-robles-Intersys

2019-10-22 14:38 UTC, jogadev requested changes
Creo que tienes un error en tu .gitignore, estás trackeando `node_modules `(101 archivos cambiados, caray, ni esos tenemos en react jajajaja)

2019-10-22 14:40 UTC, martin-one commented
En adición a lo que dijo Jorge, el node modules es de npm no? Y segun yo no es compatible con python, supongo que se fueron de mas?

2019-10-23 14:43 UTC, zkdna approved these changes

2019-10-23 14:47 UTC, jogadev approved these changes

2019-10-23 14:47 UTC, merged